[WIP] feat: enable local testing
stablyhq/stably-runner-action pull request #47
Opened 2024-12-23 21:50 UTC by mathnogueira

2025-01-02 07:01 UTC, nwparker requested changes

2025-01-02 07:01 UTC, nwparker commented on src/main.ts
> -    });
I see you refactored the HTTP call out into it's own file, I don't think we should do that.

  1. The API call is only used one place (YAGNI)
  2. This file, even with the HTTP call is less than 100 lines
  3. Putting it another file (`api.ts`) forces you to re-define types and to have an extra if clause. You're adding about 30-40 lines of extra code that's a pain to maintain

2025-01-03 22:15 UTC, mathnogueira commented on src/main.ts
> -    });
Discussed during our call.

2025-01-07 00:32 UTC, nwparker reviewed
Think this still needs a rebase too?

2025-01-07 00:32 UTC, nwparker commented on README.md
> +      http://localhost:3000
```suggestion
            https://example.com
            http://localhost:3000
```
nit: Tab these in, should work and reads nicer

2025-01-07 02:31 UTC, mathnogueira commented
> Think this still needs a rebase too?

There is no changes in `master`. If you mean squashing the commits, we can do it when we merge this PR by choosing "Squash and merge"

2025-01-07 02:39 UTC, nwparker approved these changes

2025-01-07 02:46 UTC, merged